# Generated by Django 4.2.5 on 2023-11-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_curso_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='inscriptos',
            field=models.IntegerField(verbose_name='INSCRIPTOS'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.PositiveIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], null=True, verbose_name='TURNOS'),
        ),
    ]
